FROM openjdk:11-jre
LABEL maintainer "Oliver Kopp <kopp.dev@gmail.com>, Lukas Harzenetter <lharzenetter@gmx.de>"

RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
RUN apt-get update && apt-get install -y git git-lfs

COPY org.eclipse.winery.cli/target/winery-cli.jar /usr/local/bin
COPY docker/winery /usr/local/bin

RUN chmod +x /usr/local/bin/winery-cli

CMD winery-cli
