Onlineeditor: https://www.planttext.com/

Copyright (c) 2017 Contributors to the Eclipse Foundation

See the NOTICE file(s) distributed with this work for additional
information regarding copyright ownership.

This program and the accompanying materials are made available under the
terms of the Eclipse Public License 2.0 which is available at
http://www.eclipse.org/legal/epl-2.0, or the Apache Software License 2.0
which is available at https://www.apache.org/licenses/LICENSE-2.0.

SPDX-License-Identifier: EPL-2.0 OR Apache-2.0


@startuml
'skinparam monochrome true
'Chooses LightGray as background color
'We're better off with manual setting

skinparam class {
	BackgroundColor White
	ArrowColor Black
	BorderColor Black
	LegendBackgroundColor White
}

skinparam stereotypeCBackgroundColor LightGray

skinparam noteBackgroundColor White
skinparam noteBorderColor Black

'required for SVG
skinparam defaultFontName sans-serif

Title  <size:33> Repository UI: Angular Component Tree\n\n

class WineryRepositoryComponent
class InstanceComponent
class SectionComponent

package admin {
	class TypesWithShortNameComponent
	class LoggerComponent
	class NamespacesComponent
	class RepositoryComponent
}

package artifactTemplates {
	class FilesComponent
	class ArtifactSourceComponent
}

package nodeTypes {
	class CapOrReqDefComponent
}

package policyTypes {
	class AppliesToComponent
	class LanguageComponent
}

package relationshipTypes { 
	class ValidSourcesAndTargetsComponent
}

package requirementTypes {
	class RequiredCapabilityType
}

package imports {
	class ListDefinedTypesAndElementsComponent
}

package serviceTemplates {
	package boundaryDefinitions {
		class CapabilitiesComponent
		class PoliciesComponent
		class PropertyConstraintsComponent
		class PropertyMappingsComponent
		class RequirementsComponent
		class RequirementsOrCapabilityComponent
	}
	
	package selfServicePortal {
		class SelfServiceDesciptionComponent
		class SelfServiceProtalImagesComponent
		class SelfServiceProtalOptionsComponent
	}
	
	class PlansComponent
	class TagComponent
	class TopologyTemplateComponent
	
	class BoundaryDefinitionsComponent
	class SelfServicePortalComponent
}

package sharedComponents {
	class DocumentationComponent
	class EditXmlComponent
	class ImplementationsComponent
	class InheritanceComponent
	class InstanceStatesComponent
	class PropertiesComponent
	class PropertiesDefinition
	class VisualAppearanceComponent
	class WineryArtifactComponent
	class WineryReadmeComponent
	class WineryLicenseComponent
}

WineryRepositoryComponent *-right-- WineryHeaderComponent
WineryRepositoryComponent --> SectionComponent : /:section | /:section/:namespace \n /imports/:xsdSchemaType/ | /imports/:xsdSchemaType/:namespace
WineryRepositoryComponent --> OtherComponent : /other
WineryRepositoryComponent ----> InstanceComponent

SectionComponent *- XaasPackagerComponent

BoundaryDefinitionsComponent *--- boundaryDefinitions
SelfServicePortalComponent *----- selfServicePortal

InstanceComponent ---> requirementTypes : /requirementtypes/:namespce/:localName
InstanceComponent *-up- InstanceHeaderComponent
InstanceComponent -----> admin : /admin
InstanceComponent ---> artifactTemplates : /artifacttemplates/:namespce/:localName
InstanceComponent ---> nodeTypes : /nodetypes/:namespce/:localName
InstanceComponent ---> imports : /imports/:xsdSchemaType/:namespace/:localName
InstanceComponent ----> policyTypes : /policytypes/:namespce/:localName
InstanceComponent ---> relationshipTypes : /relationshiptypes/:namespce/:localName
InstanceComponent ----> serviceTemplates : /servicetemplates/:namespce/:localName

nodeTypes -> CapOrReqDefComponent

relationshipTypes -> ValidSourcesAndTargetsComponent

requirementTypes -> RequiredCapabilityType

relationshipTypes --> sharedComponents
requirementTypes --> sharedComponents
serviceTemplates --> sharedComponents
artifactTemplates --> sharedComponents
nodeTypes ---> sharedComponents
policyTypes --> sharedComponents


@enduml
