Onlineeditor: https://www.planttext.com/

Copyright (c) 2017 University of Stuttgart.

All rights reserved. This program and the accompanying materials
are made available under the terms of the Eclipse Public License v1.0
and the Apache License 2.0 which both accompany this distribution,
and are available at http://www.eclipse.org/legal/epl-v10.html
 and http://www.apache.org/licenses/LICENSE-2.0

Contributors:
     Karoline Saatkamp - initial API and implementation, maintenance

@startuml

'skinparam monochrome true
'Chooses LightGray as background color
'We're better off with manual setting

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
    LegendBackgroundColor White
}

skinparam stereotypeCBackgroundColor LightGray

skinparam noteBackgroundColor White
skinparam noteBorderColor Black

'required for SVG
skinparam defaultFontName sans-serif


UI -> Container: CSAR
Container -> Winery: import
Winery -> Container: serviceTemplateURL
Container -> UI: serviceTemplateURL
UI -> Winery_serviceTemplateURL_injector_options
Winery_serviceTemplateURL_injector_options -> UI: topundma
UI -> Winery_serviceTemplateURL_injector_replace: replacements

@enduml
